name: _fourtho
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.4.0

flutter_gen:
  colors: 
    inputs:
      - assets/colors.xml

flutter:
  uses-material-design: true

  assets:  
    - assets/cards/ 
    - assets/icons/
  
  fonts:
  - family: Merriweather
    fonts:
      - assets: assets\fonts\Merriweather\Merriweather-Black.ttf
      - assets: assets\fonts\Merriweather\Merriweather-BlackItalic.ttf
        style: italic
      - assets: assets\fonts\Merriweather\Merriweather-Bold.ttf
        weight: 300
      - assets: assets\fonts\Merriweather\Merriweather-BoldItalic.ttf
        weight: 300
        style: italic
      - assets: assets\fonts\Merriweather\Merriweather-Italic.ttf
        weight: 700
      - assets: assets\fonts\Merriweather\Merriweather-Light.ttf
        weight: 700
        style: italic
      - assets: assets\fonts\Merriweather\Merriweather-LightItalic.ttf
        weight: 900
        style: italic
      - assets: assets\fonts\Merriweather\Merriweather-Regular.ttf
        weight: 900
        style: italic
  - family: Playfair_Display
    fonts:
      - assets: assets\fonts\Playfair_Display\static\PlayfairDisplay-Bold.ttf
        weight: 700
      - assets: assets\fonts\Playfair_Display\static\PlayfairDisplay-BoldItalic.ttf
        weight: 700
        style: italic
      - assets: assets\fonts\Playfair_Display\static\PlayfairDisplay-Italic.ttf
        style: italic
      - assets: assets\fonts\Playfair_Display\static\PlayfairDisplay-Regular.ttf
      - assets: assets\fonts\Playfair_Display\static\PlayfairDisplay-Black.ttf
        weight: 900
      - assets: assets\fonts\Playfair_Display\static\PlayfairDisplay-BlackItalic.ttf
        weight: 900
        style: italic


